[package]
name = "rutex"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rutex"
path = "src/bin/rutex.rs"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
dyn-clone = "1.0.19"
