[package]
name = "rutex"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rutex"
path = "src/bin/rutex.rs"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.26", features = ["derive"] }

[build-dependencies]
chrono = "0.4.39"
