#[rustfmt::skip]
#[allow(clippy::all)]
pub mod roman;
use std::mem::transmute;

use crate::{string_encoding::FixedSizeDecoder, types::sfnt_types::index::SFNTError};

#[derive(Clone, Copy, Debug)]
pub enum ScriptCode {
    Roman,
    Japanese,
    TraditionalChinese,
    Korean,
    Arabic,
    Hebrew,
    Greek,
    Russian,
    RSymbol,
    Devanagari,
    Gurmukhi,
    Gujarati,
    Oriya,
    Bengali,
    Tamil,
    Telugu,
    Kannada,
    Malayalam,
    Sinhalese,
    Burmese,
    Khmer,
    Thai,
    Laotian,
    Georgian,
    Armenian,
    SimplifiedChinese,
    Tibetan,
    Mongolian,
    Geez,
    Slavic,
    Vietnamese,
    Sindhi,
    Uninterpreted,
}
impl TryFrom<u16> for ScriptCode {
    type Error = SFNTError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        Ok(match value {
            0 => ScriptCode::Roman,
            1 => ScriptCode::Japanese,
            2 => ScriptCode::TraditionalChinese,
            3 => ScriptCode::Korean,
            4 => ScriptCode::Arabic,
            5 => ScriptCode::Hebrew,
            6 => ScriptCode::Greek,
            7 => ScriptCode::Russian,
            8 => ScriptCode::RSymbol,
            9 => ScriptCode::Devanagari,
            10 => ScriptCode::Gurmukhi,
            11 => ScriptCode::Gujarati,
            12 => ScriptCode::Oriya,
            13 => ScriptCode::Bengali,
            14 => ScriptCode::Tamil,
            15 => ScriptCode::Telugu,
            16 => ScriptCode::Kannada,
            17 => ScriptCode::Malayalam,
            18 => ScriptCode::Sinhalese,
            19 => ScriptCode::Burmese,
            20 => ScriptCode::Khmer,
            21 => ScriptCode::Thai,
            22 => ScriptCode::Laotian,
            23 => ScriptCode::Georgian,
            24 => ScriptCode::Armenian,
            25 => ScriptCode::SimplifiedChinese,
            26 => ScriptCode::Tibetan,
            27 => ScriptCode::Mongolian,
            28 => ScriptCode::Geez,
            29 => ScriptCode::Slavic,
            30 => ScriptCode::Vietnamese,
            31 => ScriptCode::Sindhi,
            32 => ScriptCode::Roman,
            a => return Err(SFNTError::InvalidPlatformSpecificNumber("Macintosh", a)),
        })
    }
}
#[derive(Clone, Copy, Debug)]
#[repr(u16)]
pub enum LanguageCode {
    English = 0,
    French = 1,
    German = 2,
    Italian = 3,
    Dutch = 4,
    Swedish = 5,
    Spanish = 6,
    Danish = 7,
    Portuguese = 8,
    Norwegian = 9,
    Hebrew = 10,
    Japanese = 11,
    Arabic = 12,
    Finnish = 13,
    Greek = 14,
    Icelandic = 15,
    Maltese = 16,
    Turkish = 17,
    Croatian = 18,
    TraditionalChinese = 19,
    Urdu = 20,
    Hindi = 21,
    Thai = 22,
    Korean = 23,
    Lithuanian = 24,
    Polish = 25,
    Hungarian = 26,
    Estonian = 27,
    Latvian = 28,
    Sami = 29,
    Faroese = 30,
    FarsiOrPersian = 31,
    Russian = 32,
    SimplifiedChinese = 33,
    Flemish = 34,
    IrishGaelic = 35,
    Albanian = 36,
    Romanian = 37,
    Czech = 38,
    Slovak = 39,
    Slovenian = 40,
    Yiddish = 41,
    Serbian = 42,
    Macedonian = 43,
    Bulgarian = 44,
    Ukrainian = 45,
    Byelorussian = 46,
    Uzbek = 47,
    Kazakh = 48,
    AzerbaijaniInCyrillicScript = 49,
    AzerbaijaniInArabicScript = 50,
    Armenian = 51,
    Georgian = 52,
    Moldavian = 53,
    Kirghiz = 54,
    Tajiki = 55,
    Turkmen = 56,
    MongolianInMongolianScript = 57,
    MongolianInCyrillicScript = 58,
    Pashto = 59,
    Kurdish = 60,
    Kashmiri = 61,
    Sindhi = 62,
    Tibetan = 63,
    Nepali = 64,
    Sanskrit = 65,
    Marathi = 66,
    Bengali = 67,
    Assamese = 68,
    Gujarati = 69,
    Punjabi = 70,
    Oriya = 71,
    Malayalam = 72,
    Kannada = 73,
    Tamil = 74,
    Telugu = 75,
    Sinhalese = 76,
    Burmese = 77,
    Khmer = 78,
    Lao = 79,
    Vietnamese = 80,
    Indonesian = 81,
    Tagalog = 82,
    MalayInRomanScript = 83,
    MalayInArabicScript = 84,
    Amharic = 85,
    Tigrinya = 86,
    Galla = 87,
    Somali = 88,
    Swahili = 89,
    KinyarwandaOrRuanda = 90,
    Rundi = 91,
    NyanjaOrChewa = 92,
    Malagasy = 93,
    Esperanto = 94,
    Welsh = 128,
    Basque = 129,
    Catalan = 130,
    Latin = 131,
    Quechua = 132,
    Guarani = 133,
    Aymara = 134,
    Tatar = 135,
    Uighur = 136,
    Dzongkha = 137,
    JavaneseInRomanScript = 138,
    SundaneseInRomanScript = 139,
    Galician = 140,
    Afrikaans = 141,
    Breton = 142,
    Inuktitut = 143,
    ScottishGaelic = 144,
    ManxGaelic = 145,
    IrishGaelicWithDotAbove = 146,
    Tongan = 147,
    PolytonicGreek = 148,
    Greenlandic = 149,
    AzerbaijaniInRomanScript = 150,
    Unknown = 65535,
}
impl LanguageCode {
    pub fn to_lang_string(&self) -> &'static str {
        match self {
            LanguageCode::English => "en",
            LanguageCode::French => "fr",
            LanguageCode::German => "de",
            LanguageCode::Italian => "it",
            LanguageCode::Dutch => "nl",
            LanguageCode::Swedish => "sv",
            LanguageCode::Spanish => "es",
            LanguageCode::Danish => "da",
            LanguageCode::Portuguese => "pt",
            LanguageCode::Norwegian => "no",
            LanguageCode::Hebrew => "he",
            LanguageCode::Japanese => "ja",
            LanguageCode::Arabic => "ar",
            LanguageCode::Finnish => "fi",
            LanguageCode::Greek => "el",
            LanguageCode::Icelandic => "is",
            LanguageCode::Maltese => "mt",
            LanguageCode::Turkish => "tk",
            LanguageCode::Croatian => "hr",
            LanguageCode::TraditionalChinese => "zh-Hans",
            LanguageCode::Urdu => "ur",
            LanguageCode::Hindi => "hi",
            LanguageCode::Thai => "th",
            LanguageCode::Korean => "ko",
            LanguageCode::Lithuanian => "lt",
            LanguageCode::Polish => "pl",
            LanguageCode::Hungarian => "hu",
            LanguageCode::Estonian => "et",
            LanguageCode::Latvian => "lv",
            LanguageCode::Sami => "se",
            LanguageCode::Faroese => "fo",
            LanguageCode::FarsiOrPersian => "fa",
            LanguageCode::Russian => "ru",
            LanguageCode::SimplifiedChinese => "zh-Hans",
            LanguageCode::Flemish => "nl-BE",
            LanguageCode::IrishGaelic => "ga",
            LanguageCode::Albanian => "sq",
            LanguageCode::Romanian => "ro",
            LanguageCode::Czech => "cs",
            LanguageCode::Slovak => "sk",
            LanguageCode::Slovenian => "sl",
            LanguageCode::Yiddish => "yi",
            LanguageCode::Serbian => "sr",
            LanguageCode::Macedonian => "mk",
            LanguageCode::Bulgarian => "bg",
            LanguageCode::Ukrainian => "uk",
            LanguageCode::Byelorussian => "be",
            LanguageCode::Uzbek => "uz",
            LanguageCode::Kazakh => "kk",
            LanguageCode::AzerbaijaniInCyrillicScript => "az-Cyrl",
            LanguageCode::AzerbaijaniInArabicScript => "az-Arab",
            LanguageCode::Armenian => "hy",
            LanguageCode::Georgian => "ka",
            LanguageCode::Moldavian => "mo",
            LanguageCode::Kirghiz => "ky",
            LanguageCode::Tajiki => "tg",
            LanguageCode::Turkmen => "tk",
            LanguageCode::MongolianInMongolianScript => "mn-Mong",
            LanguageCode::MongolianInCyrillicScript => "mn-Cyrl",
            LanguageCode::Pashto => "ps",
            LanguageCode::Kurdish => "ku",
            LanguageCode::Kashmiri => "ks",
            LanguageCode::Sindhi => "sd",
            LanguageCode::Tibetan => "bo",
            LanguageCode::Nepali => "ne",
            LanguageCode::Sanskrit => "sa",
            LanguageCode::Marathi => "mr",
            LanguageCode::Bengali => "bn",
            LanguageCode::Assamese => "as",
            LanguageCode::Gujarati => "gu",
            LanguageCode::Punjabi => "pa",
            LanguageCode::Oriya => "or",
            LanguageCode::Malayalam => "ml",
            LanguageCode::Kannada => "kn",
            LanguageCode::Tamil => "ta",
            LanguageCode::Telugu => "te",
            LanguageCode::Sinhalese => "si",
            LanguageCode::Burmese => "my",
            LanguageCode::Khmer => "km",
            LanguageCode::Lao => "lo",
            LanguageCode::Vietnamese => "vi",
            LanguageCode::Indonesian => "id",
            LanguageCode::Tagalog => "tl",
            LanguageCode::MalayInRomanScript => "ms",
            LanguageCode::MalayInArabicScript => "ms-Arab",
            LanguageCode::Amharic => "am",
            LanguageCode::Tigrinya => "ti",
            LanguageCode::Galla => "om",
            LanguageCode::Somali => "so",
            LanguageCode::Swahili => "sw",
            LanguageCode::KinyarwandaOrRuanda => "rw",
            LanguageCode::Rundi => "rn",
            LanguageCode::NyanjaOrChewa => "ny",
            LanguageCode::Malagasy => "mg",
            LanguageCode::Esperanto => "eo",
            LanguageCode::Welsh => "cy",
            LanguageCode::Basque => "eu",
            LanguageCode::Catalan => "ca",
            LanguageCode::Latin => "la",
            LanguageCode::Quechua => "qu",
            LanguageCode::Guarani => "gn",
            LanguageCode::Aymara => "ay",
            LanguageCode::Tatar => "tt",
            LanguageCode::Uighur => "ug",
            LanguageCode::Dzongkha => "dz",
            LanguageCode::JavaneseInRomanScript => "jv",
            LanguageCode::SundaneseInRomanScript => "su",
            LanguageCode::Galician => "gl",
            LanguageCode::Afrikaans => "af",
            LanguageCode::Breton => "br",
            LanguageCode::Inuktitut => "iu",
            LanguageCode::ScottishGaelic => "gd",
            LanguageCode::ManxGaelic => "gv",
            LanguageCode::IrishGaelicWithDotAbove => "ga",
            LanguageCode::Tongan => "to",
            LanguageCode::PolytonicGreek => "el-poly",
            LanguageCode::Greenlandic => "kl",
            LanguageCode::AzerbaijaniInRomanScript => "az",
            LanguageCode::Unknown => "und",
        }
    }
}
impl From<u16> for LanguageCode {
    fn from(value: u16) -> Self {
        match value {
            0..95 | 128..150 => unsafe {
                // Safety: types are the same sizes and are checked for validity
                transmute::<u16, LanguageCode>(value)
            },
            _ => Self::Unknown,
        }
    }
}
pub static ROMAN_DECODER: FixedSizeDecoder<'_, '_, u8> =
    FixedSizeDecoder("MacRoman", roman::MAPPING);
