use std::fmt::Debug;

use crate::{string_encoding::FixedSizeDecoder, types::sfnt_types::index::SFNTError};
#[rustfmt::skip]
#[allow(clippy::all)]
pub mod cp936;
#[rustfmt::skip]
#[allow(clippy::all)]
pub mod cp949;
#[rustfmt::skip]
#[allow(clippy::all)]
pub mod cp950;

pub static CODE_PAGE_936: FixedSizeDecoder<'_, '_, u16> =
    FixedSizeDecoder("CP 936", cp936::MAPPING);
pub static CODE_PAGE_949: FixedSizeDecoder<'_, '_, u16> =
    FixedSizeDecoder("CP 949", cp949::MAPPING);
pub static CODE_PAGE_950: FixedSizeDecoder<'_, '_, u16> =
    FixedSizeDecoder("CP 950", cp950::MAPPING);

#[derive(Clone, Copy, Debug)]
pub enum ScriptCode {
    Symbol = 0,
    UnicodeBMP = 1,
    ShiftJIS = 2,
    PRC = 3,
    Big5 = 4,
    Wansung = 5,
    Johab = 6,
    Reserved = 7,
    UnicodeFullRepertoire = 10,
}

impl TryFrom<u16> for ScriptCode {
    type Error = SFNTError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(ScriptCode::Symbol),
            1 => Ok(ScriptCode::UnicodeBMP),
            2 => Ok(ScriptCode::ShiftJIS),
            3 => Ok(ScriptCode::PRC),
            4 => Ok(ScriptCode::Big5),
            5 => Ok(ScriptCode::Wansung),
            6 => Ok(ScriptCode::Johab),
            7..10 => Ok(ScriptCode::Reserved),
            10 => Ok(ScriptCode::UnicodeFullRepertoire),
            a => Err(SFNTError::InvalidPlatformSpecificNumber("Microsoft", a)),
        }
    }
}

impl Debug for LanguageTag {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LanguageTag::Unset(arg0) => write!(f, "<{arg0}>"),
            LanguageTag::Variable(arg0) => write!(f, "{arg0:?}"),
            LanguageTag::Preset(arg0) => write!(f, "{arg0:?}"),
        }
    }
}
#[derive(Clone)]
pub enum LanguageTag {
    Unset(u16),
    Variable(String),
    Preset(&'static str),
}
impl LanguageTag {
    pub fn get_tag(&self) -> Option<&str> {
        match self {
            LanguageTag::Unset(_) => None,
            LanguageTag::Variable(v) => Some(v),
            LanguageTag::Preset(v) => Some(v),
        }
    }
}
impl TryFrom<u16> for LanguageTag {
    type Error = SFNTError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0x0001 => Ok(LanguageTag::Preset("ar")),
            0x0002 => Ok(LanguageTag::Preset("bg")),
            0x0003 => Ok(LanguageTag::Preset("ca")),
            0x0004 => Ok(LanguageTag::Preset("zh-Hans")),
            0x0005 => Ok(LanguageTag::Preset("cs")),
            0x0006 => Ok(LanguageTag::Preset("da")),
            0x0007 => Ok(LanguageTag::Preset("de")),
            0x0008 => Ok(LanguageTag::Preset("el")),
            0x0009 => Ok(LanguageTag::Preset("en")),
            0x000A => Ok(LanguageTag::Preset("es")),
            0x000B => Ok(LanguageTag::Preset("fi")),
            0x000C => Ok(LanguageTag::Preset("fr")),
            0x000D => Ok(LanguageTag::Preset("he")),
            0x000E => Ok(LanguageTag::Preset("hu")),
            0x000F => Ok(LanguageTag::Preset("is")),
            0x0010 => Ok(LanguageTag::Preset("it")),
            0x0011 => Ok(LanguageTag::Preset("ja")),
            0x0012 => Ok(LanguageTag::Preset("ko")),
            0x0013 => Ok(LanguageTag::Preset("nl")),
            0x0014 => Ok(LanguageTag::Preset("no")),
            0x0015 => Ok(LanguageTag::Preset("pl")),
            0x0016 => Ok(LanguageTag::Preset("pt")),
            0x0017 => Ok(LanguageTag::Preset("rm")),
            0x0018 => Ok(LanguageTag::Preset("ro")),
            0x0019 => Ok(LanguageTag::Preset("ru")),
            0x001A => Ok(LanguageTag::Preset("hr")),
            0x001B => Ok(LanguageTag::Preset("sk")),
            0x001C => Ok(LanguageTag::Preset("sq")),
            0x001D => Ok(LanguageTag::Preset("sv")),
            0x001E => Ok(LanguageTag::Preset("th")),
            0x001F => Ok(LanguageTag::Preset("tr")),
            0x0020 => Ok(LanguageTag::Preset("ur")),
            0x0021 => Ok(LanguageTag::Preset("id")),
            0x0022 => Ok(LanguageTag::Preset("uk")),
            0x0023 => Ok(LanguageTag::Preset("be")),
            0x0024 => Ok(LanguageTag::Preset("sl")),
            0x0025 => Ok(LanguageTag::Preset("et")),
            0x0026 => Ok(LanguageTag::Preset("lv")),
            0x0027 => Ok(LanguageTag::Preset("lt")),
            0x0028 => Ok(LanguageTag::Preset("tg")),
            0x0029 => Ok(LanguageTag::Preset("fa")),
            0x002A => Ok(LanguageTag::Preset("vi")),
            0x002B => Ok(LanguageTag::Preset("hy")),
            0x002C => Ok(LanguageTag::Preset("az")),
            0x002D => Ok(LanguageTag::Preset("eu")),
            0x002E => Ok(LanguageTag::Preset("hsb")),
            0x002F => Ok(LanguageTag::Preset("mk")),
            0x0030 => Ok(LanguageTag::Preset("st")),
            0x0031 => Ok(LanguageTag::Preset("ts")),
            0x0032 => Ok(LanguageTag::Preset("tn")),
            0x0033 => Ok(LanguageTag::Preset("ve")),
            0x0034 => Ok(LanguageTag::Preset("xh")),
            0x0035 => Ok(LanguageTag::Preset("zu")),
            0x0036 => Ok(LanguageTag::Preset("af")),
            0x0037 => Ok(LanguageTag::Preset("ka")),
            0x0038 => Ok(LanguageTag::Preset("fo")),
            0x0039 => Ok(LanguageTag::Preset("hi")),
            0x003A => Ok(LanguageTag::Preset("mt")),
            0x003B => Ok(LanguageTag::Preset("se")),
            0x003C => Ok(LanguageTag::Preset("ga")),
            0x003D => Ok(LanguageTag::Preset("yi, reserved")),
            0x003E => Ok(LanguageTag::Preset("ms")),
            0x003F => Ok(LanguageTag::Preset("kk")),
            0x0040 => Ok(LanguageTag::Preset("ky")),
            0x0041 => Ok(LanguageTag::Preset("sw")),
            0x0042 => Ok(LanguageTag::Preset("tk")),
            0x0043 => Ok(LanguageTag::Preset("uz")),
            0x0044 => Ok(LanguageTag::Preset("tt")),
            0x0045 => Ok(LanguageTag::Preset("bn")),
            0x0046 => Ok(LanguageTag::Preset("pa")),
            0x0047 => Ok(LanguageTag::Preset("gu")),
            0x0048 => Ok(LanguageTag::Preset("or")),
            0x0049 => Ok(LanguageTag::Preset("ta")),
            0x004A => Ok(LanguageTag::Preset("te")),
            0x004B => Ok(LanguageTag::Preset("kn")),
            0x004C => Ok(LanguageTag::Preset("ml")),
            0x004D => Ok(LanguageTag::Preset("as")),
            0x004E => Ok(LanguageTag::Preset("mr")),
            0x004F => Ok(LanguageTag::Preset("sa")),
            0x0050 => Ok(LanguageTag::Preset("mn")),
            0x0051 => Ok(LanguageTag::Preset("bo")),
            0x0052 => Ok(LanguageTag::Preset("cy")),
            0x0053 => Ok(LanguageTag::Preset("km")),
            0x0054 => Ok(LanguageTag::Preset("lo")),
            0x0055 => Ok(LanguageTag::Preset("my")),
            0x0056 => Ok(LanguageTag::Preset("gl")),
            0x0057 => Ok(LanguageTag::Preset("kok")),
            0x0058 => Ok(LanguageTag::Preset("mni, reserved")),
            0x0059 => Ok(LanguageTag::Preset("sd")),
            0x005A => Ok(LanguageTag::Preset("syr")),
            0x005B => Ok(LanguageTag::Preset("si")),
            0x005C => Ok(LanguageTag::Preset("chr")),
            0x005D => Ok(LanguageTag::Preset("iu")),
            0x005E => Ok(LanguageTag::Preset("am")),
            0x005F => Ok(LanguageTag::Preset("tzm")),
            0x0060 => Ok(LanguageTag::Preset("ks")),
            0x0061 => Ok(LanguageTag::Preset("ne")),
            0x0062 => Ok(LanguageTag::Preset("fy")),
            0x0063 => Ok(LanguageTag::Preset("ps")),
            0x0064 => Ok(LanguageTag::Preset("fil")),
            0x0065 => Ok(LanguageTag::Preset("dv")),
            0x0066 => Ok(LanguageTag::Preset("bin, reserved")),
            0x0067 => Ok(LanguageTag::Preset("ff")),
            0x0068 => Ok(LanguageTag::Preset("ha")),
            0x0069 => Ok(LanguageTag::Preset("ibb, reserved")),
            0x006A => Ok(LanguageTag::Preset("yo")),
            0x006B => Ok(LanguageTag::Preset("quz")),
            0x006C => Ok(LanguageTag::Preset("nso")),
            0x006D => Ok(LanguageTag::Preset("ba")),
            0x006E => Ok(LanguageTag::Preset("lb")),
            0x006F => Ok(LanguageTag::Preset("kl")),
            0x0070 => Ok(LanguageTag::Preset("ig")),
            0x0071 => Ok(LanguageTag::Preset("kr, reserved")),
            0x0072 => Ok(LanguageTag::Preset("om")),
            0x0073 => Ok(LanguageTag::Preset("ti")),
            0x0074 => Ok(LanguageTag::Preset("gn")),
            0x0075 => Ok(LanguageTag::Preset("haw")),
            0x0076 => Ok(LanguageTag::Preset("la, reserved")),
            0x0077 => Ok(LanguageTag::Preset("so, reserved")),
            0x0078 => Ok(LanguageTag::Preset("ii")),
            0x0079 => Ok(LanguageTag::Preset("pap, reserved")),
            0x007A => Ok(LanguageTag::Preset("arn")),
            0x007B => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x007C => Ok(LanguageTag::Preset("moh")),
            0x007D => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x007E => Ok(LanguageTag::Preset("br")),
            0x007F => Ok(LanguageTag::Preset(
                "Reserved for invariant locale behavior",
            )),
            0x0080 => Ok(LanguageTag::Preset("ug")),
            0x0081 => Ok(LanguageTag::Preset("mi")),
            0x0082 => Ok(LanguageTag::Preset("oc")),
            0x0083 => Ok(LanguageTag::Preset("co")),
            0x0084 => Ok(LanguageTag::Preset("gsw")),
            0x0085 => Ok(LanguageTag::Preset("sah")),
            0x0086 => Ok(LanguageTag::Preset("qut")),
            0x0087 => Ok(LanguageTag::Preset("rw")),
            0x0088 => Ok(LanguageTag::Preset("wo")),
            0x0089 => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x008A => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x008B => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x008C => Ok(LanguageTag::Preset("prs")),
            0x008D => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x008E => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x008F => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x0090 => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x0091 => Ok(LanguageTag::Preset("gd")),
            0x0092 => Ok(LanguageTag::Preset("ku")),
            0x0093 => Ok(LanguageTag::Preset("quc, reserved")),
            0x0401 => Ok(LanguageTag::Preset("ar-SA")),
            0x0402 => Ok(LanguageTag::Preset("bg-BG")),
            0x0403 => Ok(LanguageTag::Preset("ca-ES")),
            0x0404 => Ok(LanguageTag::Preset("zh-TW")),
            0x0405 => Ok(LanguageTag::Preset("cs-CZ")),
            0x0406 => Ok(LanguageTag::Preset("da-DK")),
            0x0407 => Ok(LanguageTag::Preset("de-DE")),
            0x0408 => Ok(LanguageTag::Preset("el-GR")),
            0x0409 => Ok(LanguageTag::Preset("en-US")),
            0x040A => Ok(LanguageTag::Preset("es-ES_tradnl")),
            0x040B => Ok(LanguageTag::Preset("fi-FI")),
            0x040C => Ok(LanguageTag::Preset("fr-FR")),
            0x040D => Ok(LanguageTag::Preset("he-IL")),
            0x040E => Ok(LanguageTag::Preset("hu-HU")),
            0x040F => Ok(LanguageTag::Preset("is-IS")),
            0x0410 => Ok(LanguageTag::Preset("it-IT")),
            0x0411 => Ok(LanguageTag::Preset("ja-JP")),
            0x0412 => Ok(LanguageTag::Preset("ko-KR")),
            0x0413 => Ok(LanguageTag::Preset("nl-NL")),
            0x0414 => Ok(LanguageTag::Preset("nb-NO")),
            0x0415 => Ok(LanguageTag::Preset("pl-PL")),
            0x0416 => Ok(LanguageTag::Preset("pt-BR")),
            0x0417 => Ok(LanguageTag::Preset("rm-CH")),
            0x0418 => Ok(LanguageTag::Preset("ro-RO")),
            0x0419 => Ok(LanguageTag::Preset("ru-RU")),
            0x041A => Ok(LanguageTag::Preset("hr-HR")),
            0x041B => Ok(LanguageTag::Preset("sk-SK")),
            0x041C => Ok(LanguageTag::Preset("sq-AL")),
            0x041D => Ok(LanguageTag::Preset("sv-SE")),
            0x041E => Ok(LanguageTag::Preset("th-TH")),
            0x041F => Ok(LanguageTag::Preset("tr-TR")),
            0x0420 => Ok(LanguageTag::Preset("ur-PK")),
            0x0421 => Ok(LanguageTag::Preset("id-ID")),
            0x0422 => Ok(LanguageTag::Preset("uk-UA")),
            0x0423 => Ok(LanguageTag::Preset("be-BY")),
            0x0424 => Ok(LanguageTag::Preset("sl-SI")),
            0x0425 => Ok(LanguageTag::Preset("et-EE")),
            0x0426 => Ok(LanguageTag::Preset("lv-LV")),
            0x0427 => Ok(LanguageTag::Preset("lt-LT")),
            0x0428 => Ok(LanguageTag::Preset("tg-Cyrl-TJ")),
            0x0429 => Ok(LanguageTag::Preset("fa-IR")),
            0x042A => Ok(LanguageTag::Preset("vi-VN")),
            0x042B => Ok(LanguageTag::Preset("hy-AM")),
            0x042C => Ok(LanguageTag::Preset("az-Latn-AZ")),
            0x042D => Ok(LanguageTag::Preset("eu-ES")),
            0x042E => Ok(LanguageTag::Preset("hsb-DE")),
            0x042F => Ok(LanguageTag::Preset("mk-MK")),
            0x0430 => Ok(LanguageTag::Preset("st-ZA")),
            0x0431 => Ok(LanguageTag::Preset("ts-ZA")),
            0x0432 => Ok(LanguageTag::Preset("tn-ZA")),
            0x0433 => Ok(LanguageTag::Preset("ve-ZA")),
            0x0434 => Ok(LanguageTag::Preset("xh-ZA")),
            0x0435 => Ok(LanguageTag::Preset("zu-ZA")),
            0x0436 => Ok(LanguageTag::Preset("af-ZA")),
            0x0437 => Ok(LanguageTag::Preset("ka-GE")),
            0x0438 => Ok(LanguageTag::Preset("fo-FO")),
            0x0439 => Ok(LanguageTag::Preset("hi-IN")),
            0x043A => Ok(LanguageTag::Preset("mt-MT")),
            0x043B => Ok(LanguageTag::Preset("se-NO")),
            0x043D => Ok(LanguageTag::Preset("yi-001")),
            0x043E => Ok(LanguageTag::Preset("ms-MY")),
            0x043F => Ok(LanguageTag::Preset("kk-KZ")),
            0x0440 => Ok(LanguageTag::Preset("ky-KG")),
            0x0441 => Ok(LanguageTag::Preset("sw-KE")),
            0x0442 => Ok(LanguageTag::Preset("tk-TM")),
            0x0443 => Ok(LanguageTag::Preset("uz-Latn-UZ")),
            0x0444 => Ok(LanguageTag::Preset("tt-RU")),
            0x0445 => Ok(LanguageTag::Preset("bn-IN")),
            0x0446 => Ok(LanguageTag::Preset("pa-IN")),
            0x0447 => Ok(LanguageTag::Preset("gu-IN")),
            0x0448 => Ok(LanguageTag::Preset("or-IN")),
            0x0449 => Ok(LanguageTag::Preset("ta-IN")),
            0x044A => Ok(LanguageTag::Preset("te-IN")),
            0x044B => Ok(LanguageTag::Preset("kn-IN")),
            0x044C => Ok(LanguageTag::Preset("ml-IN")),
            0x044D => Ok(LanguageTag::Preset("as-IN")),
            0x044E => Ok(LanguageTag::Preset("mr-IN")),
            0x044F => Ok(LanguageTag::Preset("sa-IN")),
            0x0450 => Ok(LanguageTag::Preset("mn-MN")),
            0x0451 => Ok(LanguageTag::Preset("bo-CN")),
            0x0452 => Ok(LanguageTag::Preset("cy-GB")),
            0x0453 => Ok(LanguageTag::Preset("km-KH")),
            0x0454 => Ok(LanguageTag::Preset("lo-LA")),
            0x0455 => Ok(LanguageTag::Preset("my-MM")),
            0x0456 => Ok(LanguageTag::Preset("gl-ES")),
            0x0457 => Ok(LanguageTag::Preset("kok-IN")),
            0x0458 => Ok(LanguageTag::Preset("mni-IN, reserved")),
            0x0459 => Ok(LanguageTag::Preset("sd-Deva-IN, reserved")),
            0x045A => Ok(LanguageTag::Preset("syr-SY")),
            0x045B => Ok(LanguageTag::Preset("si-LK")),
            0x045C => Ok(LanguageTag::Preset("chr-Cher-US")),
            0x045D => Ok(LanguageTag::Preset("iu-Cans-CA")),
            0x045E => Ok(LanguageTag::Preset("am-ET")),
            0x045F => Ok(LanguageTag::Preset("tzm-Arab-MA")),
            0x0460 => Ok(LanguageTag::Preset("ks-Arab")),
            0x0461 => Ok(LanguageTag::Preset("ne-NP")),
            0x0462 => Ok(LanguageTag::Preset("fy-NL")),
            0x0463 => Ok(LanguageTag::Preset("ps-AF")),
            0x0464 => Ok(LanguageTag::Preset("fil-PH")),
            0x0465 => Ok(LanguageTag::Preset("dv-MV")),
            0x0466 => Ok(LanguageTag::Preset("bin-NG, reserved")),
            0x0467 => Ok(LanguageTag::Preset("ff-NG, ff-Latn-NG")),
            0x0468 => Ok(LanguageTag::Preset("ha-Latn-NG")),
            0x0469 => Ok(LanguageTag::Preset("ibb-NG, reserved")),
            0x046A => Ok(LanguageTag::Preset("yo-NG")),
            0x046B => Ok(LanguageTag::Preset("quz-BO")),
            0x046C => Ok(LanguageTag::Preset("nso-ZA")),
            0x046D => Ok(LanguageTag::Preset("ba-RU")),
            0x046E => Ok(LanguageTag::Preset("lb-LU")),
            0x046F => Ok(LanguageTag::Preset("kl-GL")),
            0x0470 => Ok(LanguageTag::Preset("ig-NG")),
            0x0471 => Ok(LanguageTag::Preset("kr-Latn-NG")),
            0x0472 => Ok(LanguageTag::Preset("om-ET")),
            0x0473 => Ok(LanguageTag::Preset("ti-ET")),
            0x0474 => Ok(LanguageTag::Preset("gn-PY")),
            0x0475 => Ok(LanguageTag::Preset("haw-US")),
            0x0476 => Ok(LanguageTag::Preset("la-VA")),
            0x0477 => Ok(LanguageTag::Preset("so-SO")),
            0x0478 => Ok(LanguageTag::Preset("ii-CN")),
            0x0479 => Ok(LanguageTag::Preset("pap-029, reserved")),
            0x047A => Ok(LanguageTag::Preset("arn-CL")),
            0x047C => Ok(LanguageTag::Preset("moh-CA")),
            0x047E => Ok(LanguageTag::Preset("br-FR")),
            0x0480 => Ok(LanguageTag::Preset("ug-CN")),
            0x0481 => Ok(LanguageTag::Preset("mi-NZ")),
            0x0482 => Ok(LanguageTag::Preset("oc-FR")),
            0x0483 => Ok(LanguageTag::Preset("co-FR")),
            0x0484 => Ok(LanguageTag::Preset("gsw-FR")),
            0x0485 => Ok(LanguageTag::Preset("sah-RU")),
            0x0486 => Ok(LanguageTag::Preset("qut-GT, reserved")),
            0x0487 => Ok(LanguageTag::Preset("rw-RW")),
            0x0488 => Ok(LanguageTag::Preset("wo-SN")),
            0x048C => Ok(LanguageTag::Preset("prs-AF")),
            0x048D => Ok(LanguageTag::Preset("plt-MG, reserved")),
            0x048E => Ok(LanguageTag::Preset("zh-yue-HK, reserved")),
            0x048F => Ok(LanguageTag::Preset("tdd-Tale-CN, reserved")),
            0x0490 => Ok(LanguageTag::Preset("khb-Talu-CN, reserved")),
            0x0491 => Ok(LanguageTag::Preset("gd-GB")),
            0x0492 => Ok(LanguageTag::Preset("ku-Arab-IQ")),
            0x0493 => Ok(LanguageTag::Preset("quc-CO, reserved")),
            0x0501 => Ok(LanguageTag::Preset("qps-ploc")),
            0x05FE => Ok(LanguageTag::Preset("qps-ploca")),
            0x0801 => Ok(LanguageTag::Preset("ar-IQ")),
            0x0803 => Ok(LanguageTag::Preset("ca-ES-valencia")),
            0x0804 => Ok(LanguageTag::Preset("zh-CN")),
            0x0807 => Ok(LanguageTag::Preset("de-CH")),
            0x0809 => Ok(LanguageTag::Preset("en-GB")),
            0x080A => Ok(LanguageTag::Preset("es-MX")),
            0x080C => Ok(LanguageTag::Preset("fr-BE")),
            0x0810 => Ok(LanguageTag::Preset("it-CH")),
            0x0811 => Ok(LanguageTag::Preset("ja-Ploc-JP, reserved")),
            0x0813 => Ok(LanguageTag::Preset("nl-BE")),
            0x0814 => Ok(LanguageTag::Preset("nn-NO")),
            0x0816 => Ok(LanguageTag::Preset("pt-PT")),
            0x0818 => Ok(LanguageTag::Preset("ro-MD")),
            0x0819 => Ok(LanguageTag::Preset("ru-MD")),
            0x081A => Ok(LanguageTag::Preset("sr-Latn-CS")),
            0x081D => Ok(LanguageTag::Preset("sv-FI")),
            0x0820 => Ok(LanguageTag::Preset("ur-IN")),
            0x0827 => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x082C => Ok(LanguageTag::Preset("az-Cyrl-AZ, reserved")),
            0x082E => Ok(LanguageTag::Preset("dsb-DE")),
            0x0832 => Ok(LanguageTag::Preset("tn-BW")),
            0x083B => Ok(LanguageTag::Preset("se-SE")),
            0x083C => Ok(LanguageTag::Preset("ga-IE")),
            0x083E => Ok(LanguageTag::Preset("ms-BN")),
            0x083F => Ok(LanguageTag::Preset("kk-Latn-KZ, reserved")),
            0x0843 => Ok(LanguageTag::Preset("uz-Cyrl-UZ, reserved")),
            0x0845 => Ok(LanguageTag::Preset("bn-BD")),
            0x0846 => Ok(LanguageTag::Preset("pa-Arab-PK")),
            0x0849 => Ok(LanguageTag::Preset("ta-LK")),
            0x0850 => Ok(LanguageTag::Preset("mn-Mong-CN, reserved")),
            0x0851 => Ok(LanguageTag::Preset("bo-BT, reserved")),
            0x0859 => Ok(LanguageTag::Preset("sd-Arab-PK")),
            0x085D => Ok(LanguageTag::Preset("iu-Latn-CA")),
            0x085F => Ok(LanguageTag::Preset("tzm-Latn-DZ")),
            0x0860 => Ok(LanguageTag::Preset("ks-Deva-IN")),
            0x0861 => Ok(LanguageTag::Preset("ne-IN")),
            0x0867 => Ok(LanguageTag::Preset("ff-Latn-SN")),
            0x086B => Ok(LanguageTag::Preset("quz-EC")),
            0x0873 => Ok(LanguageTag::Preset("ti-ER")),
            0x09FF => Ok(LanguageTag::Preset("qps-plocm")),
            0x0C00 => Ok(LanguageTag::Preset(
                "Locale without assigned LCID if the current user default locale. See section 2.2.1.",
            )),
            0x0C01 => Ok(LanguageTag::Preset("ar-EG")),
            0x0C04 => Ok(LanguageTag::Preset("zh-HK")),
            0x0C07 => Ok(LanguageTag::Preset("de-AT")),
            0x0C09 => Ok(LanguageTag::Preset("en-AU")),
            0x0C0A => Ok(LanguageTag::Preset("es-ES")),
            0x0C0C => Ok(LanguageTag::Preset("fr-CA")),
            0x0C1A => Ok(LanguageTag::Preset("sr-Cyrl-CS")),
            0x0C3B => Ok(LanguageTag::Preset("se-FI")),
            0x0C50 => Ok(LanguageTag::Preset("mn-Mong-MN")),
            0x0C51 => Ok(LanguageTag::Preset("dz-BT")),
            0x0C5F => Ok(LanguageTag::Preset("tmz-MA, reserved")),
            0x0C6B => Ok(LanguageTag::Preset("quz-PE")),
            0x1000 => Ok(LanguageTag::Preset(
                "Locale without assigned LCID if the current user default locale. See section 2.2.1.",
            )),
            0x1001 => Ok(LanguageTag::Preset("ar-LY")),
            0x1004 => Ok(LanguageTag::Preset("zh-SG")),
            0x1007 => Ok(LanguageTag::Preset("de-LU")),
            0x1009 => Ok(LanguageTag::Preset("en-CA")),
            0x100A => Ok(LanguageTag::Preset("es-GT")),
            0x100C => Ok(LanguageTag::Preset("fr-CH")),
            0x101A => Ok(LanguageTag::Preset("hr-BA")),
            0x103B => Ok(LanguageTag::Preset("smj-NO")),
            0x105F => Ok(LanguageTag::Preset("tzm-Tfng-MA")),
            0x1401 => Ok(LanguageTag::Preset("ar-DZ")),
            0x1404 => Ok(LanguageTag::Preset("zh-MO")),
            0x1407 => Ok(LanguageTag::Preset("de-LI")),
            0x1409 => Ok(LanguageTag::Preset("en-NZ")),
            0x140A => Ok(LanguageTag::Preset("es-CR")),
            0x140C => Ok(LanguageTag::Preset("fr-LU")),
            0x141A => Ok(LanguageTag::Preset("bs-Latn-BA")),
            0x143B => Ok(LanguageTag::Preset("smj-SE")),
            0x1801 => Ok(LanguageTag::Preset("ar-MA")),
            0x1809 => Ok(LanguageTag::Preset("en-IE")),
            0x180A => Ok(LanguageTag::Preset("es-PA")),
            0x180C => Ok(LanguageTag::Preset("fr-MC")),
            0x181A => Ok(LanguageTag::Preset("sr-Latn-BA")),
            0x183B => Ok(LanguageTag::Preset("sma-NO")),
            0x1C01 => Ok(LanguageTag::Preset("ar-TN")),
            0x1C09 => Ok(LanguageTag::Preset("en-ZA")),
            0x1C0A => Ok(LanguageTag::Preset("es-DO")),
            0x1C0C => Ok(LanguageTag::Preset("fr-029")),
            0x1C1A => Ok(LanguageTag::Preset("sr-Cyrl-BA")),
            0x1C3B => Ok(LanguageTag::Preset("sma-SE")),
            0x2000 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x3000. See section 2.2.1.",
            )),
            0x2001 => Ok(LanguageTag::Preset("ar-OM")),
            0x2008 => Ok(LanguageTag::Preset("Neither defined nor reserved")),
            0x2009 => Ok(LanguageTag::Preset("en-JM")),
            0x200A => Ok(LanguageTag::Preset("es-VE")),
            0x200C => Ok(LanguageTag::Preset("fr-RE")),
            0x201A => Ok(LanguageTag::Preset("bs-Cyrl-BA")),
            0x203B => Ok(LanguageTag::Preset("sms-FI")),
            0x2400 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x3000. See section 2.2.1.",
            )),
            0x2401 => Ok(LanguageTag::Preset("ar-YE")),
            0x2409 => Ok(LanguageTag::Preset("en-029, reserved")),
            0x240A => Ok(LanguageTag::Preset("es-CO")),
            0x240C => Ok(LanguageTag::Preset("fr-CD")),
            0x241A => Ok(LanguageTag::Preset("sr-Latn-RS")),
            0x243B => Ok(LanguageTag::Preset("smn-FI")),
            0x2800 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x3000. See section 2.2.1.",
            )),
            0x2801 => Ok(LanguageTag::Preset("ar-SY")),
            0x2809 => Ok(LanguageTag::Preset("en-BZ")),
            0x280A => Ok(LanguageTag::Preset("es-PE")),
            0x280C => Ok(LanguageTag::Preset("fr-SN")),
            0x281A => Ok(LanguageTag::Preset("sr-Cyrl-RS")),
            0x2C00 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x3000. See section 2.2.1.",
            )),
            0x2C01 => Ok(LanguageTag::Preset("ar-JO")),
            0x2C09 => Ok(LanguageTag::Preset("en-TT")),
            0x2C0A => Ok(LanguageTag::Preset("es-AR")),
            0x2C0C => Ok(LanguageTag::Preset("fr-CM")),
            0x2C1A => Ok(LanguageTag::Preset("sr-Latn-ME")),
            0x3000 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x3000. See section 2.2.1.",
            )),
            0x3001 => Ok(LanguageTag::Preset("ar-LB")),
            0x3009 => Ok(LanguageTag::Preset("en-ZW")),
            0x300A => Ok(LanguageTag::Preset("es-EC")),
            0x300C => Ok(LanguageTag::Preset("fr-CI")),
            0x301A => Ok(LanguageTag::Preset("sr-Cyrl-ME")),
            0x3400 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x3400. See section 2.2.1.",
            )),
            0x3401 => Ok(LanguageTag::Preset("ar-KW")),
            0x3409 => Ok(LanguageTag::Preset("en-PH")),
            0x340A => Ok(LanguageTag::Preset("es-CL")),
            0x340C => Ok(LanguageTag::Preset("fr-ML")),
            0x3800 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x3800. See section 2.2.1.",
            )),
            0x3801 => Ok(LanguageTag::Preset("ar-AE")),
            0x3809 => Ok(LanguageTag::Preset("en-ID, reserved")),
            0x380A => Ok(LanguageTag::Preset("es-UY")),
            0x380C => Ok(LanguageTag::Preset("fr-MA")),
            0x3C00 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x3C00. See section 2.2.1.",
            )),
            0x3C01 => Ok(LanguageTag::Preset("ar-BH")),
            0x3C09 => Ok(LanguageTag::Preset("en-HK")),
            0x3C0A => Ok(LanguageTag::Preset("es-PY")),
            0x3C0C => Ok(LanguageTag::Preset("fr-HT")),
            0x4000 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x4000. See section 2.2.1.",
            )),
            0x4001 => Ok(LanguageTag::Preset("ar-QA")),
            0x4009 => Ok(LanguageTag::Preset("en-IN")),
            0x400A => Ok(LanguageTag::Preset("es-BO")),
            0x4400 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x4400. See section 2.2.1.",
            )),
            0x4401 => Ok(LanguageTag::Preset("ar-Ploc-SA, reserved")),
            0x4409 => Ok(LanguageTag::Preset("en-MY")),
            0x440A => Ok(LanguageTag::Preset("es-SV")),
            0x4800 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x4800. See section 2.2.1.",
            )),
            0x4801 => Ok(LanguageTag::Preset("ar-145, reserved")),
            0x4809 => Ok(LanguageTag::Preset("en-SG")),
            0x480A => Ok(LanguageTag::Preset("es-HN")),
            0x4C00 => Ok(LanguageTag::Preset(
                "Unassigned LCID locale temporarily assigned to LCID 0x4C00. See section 2.2.1.",
            )),
            0x4C09 => Ok(LanguageTag::Preset("en-AE")),
            0x4C0A => Ok(LanguageTag::Preset("es-NI")),
            0x5009 => Ok(LanguageTag::Preset("en-BH, reserved")),
            0x500A => Ok(LanguageTag::Preset("es-PR")),
            0x5409 => Ok(LanguageTag::Preset("en-EG, reserved")),
            0x540A => Ok(LanguageTag::Preset("es-US")),
            0x5809 => Ok(LanguageTag::Preset("en-JO, reserved")),
            0x580A => Ok(LanguageTag::Preset("es-419, reserved")),
            0x5C09 => Ok(LanguageTag::Preset("en-KW, reserved")),
            0x5C0A => Ok(LanguageTag::Preset("es-CU")),
            0x6009 => Ok(LanguageTag::Preset("en-TR, reserved")),
            0x6409 => Ok(LanguageTag::Preset("en-YE, reserved")),
            0x641A => Ok(LanguageTag::Preset("bs-Cyrl")),
            0x681A => Ok(LanguageTag::Preset("bs-Latn")),
            0x6C1A => Ok(LanguageTag::Preset("sr-Cyrl")),
            0x701A => Ok(LanguageTag::Preset("sr-Latn")),
            0x703B => Ok(LanguageTag::Preset("smn")),
            0x742C => Ok(LanguageTag::Preset("az-Cyrl")),
            0x743B => Ok(LanguageTag::Preset("sms")),
            0x7804 => Ok(LanguageTag::Preset("zh")),
            0x7814 => Ok(LanguageTag::Preset("nn")),
            0x781A => Ok(LanguageTag::Preset("bs")),
            0x782C => Ok(LanguageTag::Preset("az-Latn")),
            0x783B => Ok(LanguageTag::Preset("sma")),
            0x783F => Ok(LanguageTag::Preset("kk-Cyrl, reserved")),
            0x7843 => Ok(LanguageTag::Preset("uz-Cyrl")),
            0x7850 => Ok(LanguageTag::Preset("mn-Cyrl")),
            0x785D => Ok(LanguageTag::Preset("iu-Cans")),
            0x785F => Ok(LanguageTag::Preset("tzm-Tfng")),
            0x7C04 => Ok(LanguageTag::Preset("zh-Hant")),
            0x7C14 => Ok(LanguageTag::Preset("nb")),
            0x7C1A => Ok(LanguageTag::Preset("sr")),
            0x7C28 => Ok(LanguageTag::Preset("tg-Cyrl")),
            0x7C2E => Ok(LanguageTag::Preset("dsb")),
            0x7C3B => Ok(LanguageTag::Preset("smj")),
            0x7C3F => Ok(LanguageTag::Preset("kk-Latn, reserved")),
            0x7C43 => Ok(LanguageTag::Preset("uz-Latn")),
            0x7C46 => Ok(LanguageTag::Preset("pa-Arab")),
            0x7C50 => Ok(LanguageTag::Preset("mn-Mong")),
            0x7C59 => Ok(LanguageTag::Preset("sd-Arab")),
            0x7C5C => Ok(LanguageTag::Preset("chr-Cher")),
            0x7C5D => Ok(LanguageTag::Preset("iu-Latn")),
            0x7C5F => Ok(LanguageTag::Preset("tzm-Latn")),
            0x7C67 => Ok(LanguageTag::Preset("ff-Latn")),
            0x7C68 => Ok(LanguageTag::Preset("ha-Latn")),
            0x7C92 => Ok(LanguageTag::Preset("ku-Arab")),
            0xF2EE => Ok(LanguageTag::Preset("reserved")),
            0xE40C => Ok(LanguageTag::Preset("fr-015, reserved")),
            0xEEEE => Ok(LanguageTag::Preset("reserved")),
            value @ 0x8000.. => Ok(LanguageTag::Unset(value - 0x8000)),
            a => Err(SFNTError::InvalidLanguageNumber("Microsoft", a)),
        }
    }
}
